FROM docker.io/centos:centos7.5.1804

RUN curl -fsSL "https://go.dev/dl/go1.21.5.linux-amd64.tar.gz" -o golang.tar.gz \
  && echo "e2bc0b3e4b64111ec117295c088bde5f00eeed1567999ff77bc859d7df70078e  golang.tar.gz" | sha256sum -c - \
  && tar -C /usr/local -xzf golang.tar.gz \
  && rm golang.tar.gz

RUN yum install -y git
